### ISSUE TITLE
brunch not working

### ISSUE THREAD

**Issue by PeterHindes** [crdroidandroid/android#68]
Brunch is trying to fetch from the lineageos repos instead of these repos. I have tried guacamole and crownlte.

**Comment by jskubick** [comment]
Not sure whether I'm having the same problem. I followed the instructions in readme.md to set up a virgin build environment in a new VM installation of Ubuntu 20.04, and made it as far as `repo sync` and `crdroid/build/envsetup.sh` without errors... but when I got to the next step and tried running brunch, all I got was:

~~~
Command 'brunch' not found, did you mean:

    command 'crunch' from deb crunch (3.6-2)
    command 'branch' from deb rheolef (7.1-1)

Try: sudo apt install <deb name>
~~~

It's been aeons since the last time I built an AOSP ROM from scratch, but I'm guessing that somewhere along the line, the hooks that `envsetup.sh` is attempting to create for `brunch` are silently failing, so bash isn't intercepting the call to `brunch` and is attempting to find an actual program with that name.

I don't know whether this is just another manifestation of the problem PeterHindes described, or something completely different, but the fact that both appear to involve `brunch` probably isn't a coincidence.

**Comment by adazem009** [comment]
> Not sure whether I'm having the same problem. I followed the instructions in readme.md to set up a virgin build environment in a new VM installation of Ubuntu 20.04, and made it as far as `repo sync` and `crdroid/build/envsetup.sh` without errors... but when I got to the next step and tried running brunch, all I got was:
> 
> ```
> Command 'brunch' not found, did you mean:
> 
>     command 'crunch' from deb crunch (3.6-2)
>     command 'branch' from deb rheolef (7.1-1)
> 
> Try: sudo apt install <deb name>
> ```
> 
> It's been aeons since the last time I built an AOSP ROM from scratch, but I'm guessing that somewhere along the line, the hooks that `envsetup.sh` is attempting to create for `brunch` are silently failing, so bash isn't intercepting the call to `brunch` and is attempting to find an actual program with that name.
> 
> I don't know whether this is just another manifestation of the problem PeterHindes described, or something completely different, but the fact that both appear to involve `brunch` probably isn't a coincidence.

You should use `source`. Go to the source directory (`crdroid` in your case) and execute `source build/envsetup.sh`
Then try to use `brunch`.
